#https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c
version: "2"

services:
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"

  redis:
    image: redis
    ports:
      - "63791:6379"

  database:
    image: mysql:latest
    volumes:
      - "database_data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database_name"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=password"
    ports:
      - "3306:3306"

  composer:
    image: composer/composer
    volumes_from:
      - web
    working_dir: /var/www

  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    volumes:
      - ./:/var/www

volumes:
  database_data:
    driver: local
